name: Lint

on:
  push:
    paths:
      - '*.py'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install mypy
        run: |
          pip install mypy
          mypy --install-types
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}