name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - run: python3 -m build

      - uses: pypa/gh-action-pypi-publish@release/v1.4
        with:
          user: __token__
          password: ${{ secrets.RIBOSE_PYPI_API_TOKEN }}
          verbose: true
